/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 27 09:48:45 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(8215);
      assertEquals(14, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(2048);
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(912);
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(1024);
      assertEquals(11, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(4096);
      assertEquals(13, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(128);
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(35);
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(8);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(2);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(16);
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(268435456);
      assertEquals(29, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(536870912);
      assertEquals(30, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(134217728);
      assertEquals(28, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(33554432);
      assertEquals(26, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(67108864);
      assertEquals(27, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(16777216);
      assertEquals(25, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(8388608);
      assertEquals(24, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(2097152);
      assertEquals(22, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(1048576);
      assertEquals(21, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(524288);
      assertEquals(20, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(131072);
      assertEquals(18, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(262144);
      assertEquals(19, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(65536);
      assertEquals(17, int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(1073741824);
      assertEquals(31, int0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(16384);
      assertEquals(15, int0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(8192);
      assertEquals(14, int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(32768);
      assertEquals(16, int0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(512);
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(256);
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(3383);
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(64);
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(32);
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(4);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(3);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(13);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(213);
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(4194304);
      assertEquals(23, int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__((-1124));
      assertEquals(32, int0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__(0);
      assertEquals(0, int0);
  }
}
