/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 28 09:55:08 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte) (-103));
      assertEquals((byte) (-103), byte0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)0);
      assertEquals((byte)0, byte0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)57);
      assertEquals((byte)55, byte0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)56);
      assertEquals((byte)55, byte0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)54);
      assertEquals((byte)55, byte0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)53);
      assertEquals((byte)55, byte0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)52);
      assertEquals((byte)50, byte0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)51);
      assertEquals((byte)50, byte0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)49);
      assertEquals((byte)50, byte0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)48);
      assertEquals((byte)50, byte0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)47);
      assertEquals((byte)45, byte0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)46);
      assertEquals((byte)45, byte0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)44);
      assertEquals((byte)45, byte0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)43);
      assertEquals((byte)45, byte0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)42);
      assertEquals((byte)40, byte0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)41);
      assertEquals((byte)40, byte0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)39);
      assertEquals((byte)40, byte0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)38);
      assertEquals((byte)40, byte0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)37);
      assertEquals((byte)35, byte0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)36);
      assertEquals((byte)35, byte0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)34);
      assertEquals((byte)35, byte0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)33);
      assertEquals((byte)35, byte0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)32);
      assertEquals((byte)30, byte0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)31);
      assertEquals((byte)30, byte0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)29);
      assertEquals((byte)30, byte0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)28);
      assertEquals((byte)30, byte0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)27);
      assertEquals((byte)25, byte0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)26);
      assertEquals((byte)25, byte0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)24);
      assertEquals((byte)25, byte0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)23);
      assertEquals((byte)25, byte0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)22);
      assertEquals((byte)20, byte0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)21);
      assertEquals((byte)20, byte0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)19);
      assertEquals((byte)20, byte0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)18);
      assertEquals((byte)20, byte0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)17);
      assertEquals((byte)15, byte0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)16);
      assertEquals((byte)15, byte0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)14);
      assertEquals((byte)15, byte0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)13);
      assertEquals((byte)15, byte0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)12);
      assertEquals((byte)10, byte0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)11);
      assertEquals((byte)10, byte0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)9);
      assertEquals((byte)10, byte0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)8);
      assertEquals((byte)10, byte0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)7);
      assertEquals((byte)5, byte0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Target target0 = new Target();
      byte byte0 = target0.__target__((byte)6);
      assertEquals((byte)5, byte0);
  }
}
