/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 27 14:40:50 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "-n";
      Object object0 = target0.__target__(stringArray0);
      assertEquals("null null null", object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[4];
      stringArray0[0] = "7~";
      Target target0 = new Target();
      Object object0 = target0.__target__(stringArray0);
      assertEquals("7~ null null null\n", object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      String[] stringArray0 = new String[0];
      Object object0 = target0.__target__(stringArray0);
      assertEquals("\n", object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[4];
      Target target0 = new Target();
      Object object0 = target0.__target__(stringArray0);
      assertEquals("null null null null\n", object0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      Object object0 = target0.__target__((String[]) null);
      assertNull(object0);
  }
}
