/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 27 20:00:24 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)78);
      assertEquals("4E", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)12);
      assertEquals("0C", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)10);
      assertEquals("0A", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-56));
      assertEquals("C8", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-57));
      assertEquals("C7", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-58));
      assertEquals("C6", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)1);
      assertEquals("01", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-1));
      assertEquals("FF", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-28));
      assertEquals("E4", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-39));
      assertEquals("D9", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-71));
      assertEquals("B9", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-85));
      assertEquals("AB", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-107));
      assertEquals("95", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte) (-119));
      assertEquals("89", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)115);
      assertEquals("73", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)100);
      assertEquals("64", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)93);
      assertEquals("5D", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)66);
      assertEquals("42", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)53);
      assertEquals("35", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)36);
      assertEquals("24", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)21);
      assertEquals("15", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__((byte)0);
      assertEquals("00", string0);
  }
}
