/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 25 11:10:36 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      StringBuilder stringBuilder0 = new StringBuilder("Target");
      StringBuilder stringBuilder1 = stringBuilder0.append((CharSequence) "Target");
      boolean boolean0 = target0.__target__(stringBuilder1, "Target");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      StringBuilder stringBuilder0 = new StringBuilder("Target");
      stringBuilder0.append((StringBuffer) null);
      boolean boolean0 = target0.__target__(stringBuilder0, "XuhI@Vo");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      StringBuilder stringBuilder0 = new StringBuilder();
      // Undeclared exception!
      try { 
        target0.__target__(stringBuilder0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      StringBuilder stringBuilder0 = new StringBuilder("FYwW#lK='ed}45");
      boolean boolean0 = target0.__target__(stringBuilder0, "L4*mDm:zYK>1,Z");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      StringBuilder stringBuilder0 = new StringBuilder();
      boolean boolean0 = target0.__target__(stringBuilder0, "yV@rO8Zp(wM[");
      assertFalse(boolean0);
  }
}
