/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 26 12:17:58 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.Duration;
import java.time.Instant;
import java.time.temporal.TemporalAmount;
import java.util.Date;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      MockDate mockDate0 = new MockDate((-1671), (-523), 1030, (-523), (-523), 1);
      MockDate mockDate1 = new MockDate((-1671), (-523), 1030);
      boolean boolean0 = target0.__target__(mockDate0, mockDate1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      MockDate mockDate0 = new MockDate((-2216L));
      Instant instant0 = MockInstant.ofEpochSecond((-217L));
      Duration duration0 = Duration.ofDays((-217L));
      Instant instant1 = MockInstant.plus(instant0, (TemporalAmount) duration0);
      Date date0 = Date.from(instant1);
      boolean boolean0 = target0.__target__(date0, mockDate0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      MockDate mockDate0 = new MockDate(0, 0, 0, 1311, (-2094));
      MockDate mockDate1 = new MockDate((-1), (-2094), 0, 0, 14);
      boolean boolean0 = target0.__target__(mockDate0, mockDate1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      try { 
        target0.__target__((Date) null, (Date) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Calendar", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      MockDate mockDate0 = new MockDate((-1671), (-523), 1030, (-523), (-523), 1);
      MockDate mockDate1 = new MockDate((-1671), (-523), 1030);
      boolean boolean0 = target0.__target__(mockDate1, mockDate0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Target target0 = new Target();
      MockDate mockDate0 = new MockDate((-2216L));
      Instant instant0 = MockInstant.ofEpochSecond((-217L));
      Duration duration0 = Duration.ofDays((-217L));
      Instant instant1 = MockInstant.plus(instant0, (TemporalAmount) duration0);
      Date date0 = Date.from(instant1);
      boolean boolean0 = target0.__target__(mockDate0, date0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Target target0 = new Target();
      MockDate mockDate0 = new MockDate((-1671), (-523), 1030, (-523), (-523), 1);
      boolean boolean0 = target0.__target__(mockDate0, mockDate0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Target target0 = new Target();
      MockDate mockDate0 = new MockDate(0, 0, 0, 1311, (-2094));
      MockDate mockDate1 = new MockDate((-1), (-2094), 0, 0, 14);
      boolean boolean0 = target0.__target__(mockDate1, mockDate0);
      assertFalse(boolean0);
  }
}
