/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 29 12:29:46 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      Integer integer0 = new Integer(1860);
      Short short0 = target0.__target__(integer0);
      assertEquals((short)1860, (short)short0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      Integer integer0 = new Integer((-593));
      Short short0 = target0.__target__(integer0);
      assertEquals((short) (-593), (short)short0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      Integer integer0 = new Integer(0);
      Short short0 = target0.__target__(integer0);
      assertEquals((short)0, (short)short0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      Short short0 = target0.__target__((Object) null);
      assertNull(short0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      Short short0 = target0.__target__(target0);
      assertNull(short0);
  }
}
