/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 26 11:20:46 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      String[] stringArray0 = new String[7];
      String[] stringArray1 = new String[0];
      boolean boolean0 = target0.__target__(stringArray0, stringArray1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "";
      String[] stringArray1 = new String[6];
      boolean boolean0 = target0.__target__(stringArray0, stringArray1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "(Wz";
      stringArray0[4] = "Target";
      stringArray0[5] = "";
      stringArray0[6] = "Target";
      stringArray0[7] = "2q)~?0MzR1zz6%";
      boolean boolean0 = target0.__target__(stringArray0, stringArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      String[] stringArray0 = new String[7];
      String[] stringArray1 = new String[0];
      boolean boolean0 = target0.__target__(stringArray1, stringArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      String[] stringArray0 = new String[8];
      // Undeclared exception!
      try { 
        target0.__target__(stringArray0, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
