/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 28 22:46:36 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Hashtable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      Hashtable<String, String> hashtable0 = new Hashtable<String, String>();
      String string0 = target0.__target__(hashtable0, "QrSM:$()A.*:/Von$#", (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      Hashtable<Object, String> hashtable0 = new Hashtable<Object, String>();
      String string0 = target0.__target__(hashtable0, "7", "7");
      assertEquals("7", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      try { 
        target0.__target__((Hashtable) null, "", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      Hashtable<String, Object> hashtable0 = new Hashtable<String, Object>();
      hashtable0.put("vvFLCu>c4D2w:g%", target0);
      // Undeclared exception!
      try { 
        target0.__target__(hashtable0, "vvFLCu>c4D2w:g%", "Target");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class Target cannot be cast to class java.lang.String (Target is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @643c89d3; java.lang.String is in module java.base of loader 'bootstrap')
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      Hashtable<String, String> hashtable0 = new Hashtable<String, String>();
      hashtable0.put("", "");
      String string0 = target0.__target__(hashtable0, "", "");
      assertEquals("", string0);
  }
}
