/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 30 10:22:45 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__("y6?H-QVhisd1AzkY1A8", "QVhisd1AzkY1A8", "]", (-3540));
      assertEquals("y6?H-]", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__("", "pIEDL}*;EN\"D", "dpjz?%b", 0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      target0.__target__("Y#{(xR.gS#EWQvK0|", "Y#{(xR.gS#EWQvK0|", "Y#{(xR.gS#EWQvK0|", (-10849));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      try { 
        target0.__target__("!a{", (String) null, "V77dmlNwV", 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      String string0 = target0.__target__("QVhisd1AzkY1A8", "", "y6?H-", 1);
      assertEquals("y6?H-QVhisd1AzkY1A8", string0);
  }
}
