/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 26 22:17:31 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Properties;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      Properties properties0 = new Properties();
      String string0 = target0.__target__(properties0, "^{7u", (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      Properties properties0 = new Properties();
      String string0 = target0.__target__(properties0, "Bhv)AiPN{-IB8Sl", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      Properties properties0 = new Properties();
      // Undeclared exception!
      try { 
        target0.__target__(properties0, (String) null, "xwl:u? &}");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      Properties properties0 = new Properties();
      String string0 = target0.__target__(properties0, "Bhv)AiPN{-IB8Sl", "Bhv)AiPN{-IB8Sl");
      assertEquals("Bhv)AiPN{-IB8Sl", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      Properties properties0 = new Properties();
      properties0.put("", "Bhv)AiPN{-IB8Sl");
      String string0 = target0.__target__(properties0, "", "");
      assertEquals("Bhv)AiPN{-IB8Sl", string0);
  }
}
