/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 27 19:05:13 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[9];
      byteArray0[2] = (byte) (-37);
      long long0 = target0.__target__(byteArray0, (byte)0, false);
      assertEquals(14352384L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[8];
      byteArray0[1] = (byte)43;
      long long0 = target0.__target__(byteArray0, (byte)0, false);
      assertEquals(11008L, long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[19];
      byteArray0[3] = (byte)8;
      long long0 = target0.__target__(byteArray0, (byte)1, true);
      assertEquals(2048L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[8];
      byteArray0[1] = (byte)8;
      long long0 = target0.__target__(byteArray0, (byte)0, true);
      assertEquals(524288L, long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[19];
      byteArray0[1] = (byte)43;
      long long0 = target0.__target__(byteArray0, (byte)1, true);
      assertEquals(721420288L, long0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[9];
      byteArray0[3] = (byte) (-14);
      long long0 = target0.__target__(byteArray0, (byte)0, false);
      assertEquals((-234881024L), long0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      try { 
        target0.__target__((byte[]) null, (-309), true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[19];
      // Undeclared exception!
      try { 
        target0.__target__(byteArray0, 4971, true);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 4971 out of bounds for length 19
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[19];
      long long0 = target0.__target__(byteArray0, (byte)1, true);
      assertEquals(0L, long0);
  }
}
