/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 29 15:58:54 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.LongBuffer;
import java.util.BitSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      BitSet bitSet0 = new BitSet(2305);
      long[] longArray0 = new long[8];
      longArray0[0] = (long) 2305;
      LongBuffer longBuffer0 = LongBuffer.wrap(longArray0);
      BitSet bitSet1 = BitSet.valueOf(longBuffer0);
      int int0 = target0.__target__(bitSet1, bitSet0);
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      try { 
        target0.__target__((BitSet) null, (BitSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[47];
      longArray0[41] = (long) 2301;
      LongBuffer longBuffer0 = LongBuffer.wrap(longArray0);
      BitSet bitSet0 = BitSet.valueOf(longBuffer0);
      BitSet bitSet1 = BitSet.valueOf(longArray0);
      bitSet0.flip(2301);
      int int0 = target0.__target__(bitSet1, bitSet0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[15];
      longArray0[0] = (long) 2287;
      LongBuffer longBuffer0 = LongBuffer.wrap(longArray0);
      BitSet bitSet0 = BitSet.valueOf(longBuffer0);
      BitSet bitSet1 = BitSet.valueOf(longArray0);
      bitSet1.flip(10);
      int int0 = target0.__target__(bitSet1, bitSet0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      BitSet bitSet0 = new BitSet(2305);
      long[] longArray0 = new long[8];
      longArray0[0] = (long) 2305;
      BitSet bitSet1 = BitSet.valueOf(longArray0);
      int int0 = target0.__target__(bitSet0, bitSet1);
      assertEquals((-12), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[15];
      LongBuffer longBuffer0 = LongBuffer.wrap(longArray0);
      BitSet bitSet0 = BitSet.valueOf(longBuffer0);
      int int0 = target0.__target__(bitSet0, bitSet0);
      assertEquals(0, int0);
  }
}
