/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 27 13:41:33 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      float[] floatArray0 = new float[2];
      floatArray0[0] = 1.0F;
      float float0 = target0.__target__(floatArray0, floatArray0);
      assertEquals(1.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      float[] floatArray0 = new float[2];
      floatArray0[1] = (-2177.2473F);
      float[] floatArray1 = new float[2];
      floatArray1[1] = 1.0F;
      float float0 = target0.__target__(floatArray0, floatArray1);
      assertEquals((-2177.2473F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      float[] floatArray0 = new float[2];
      // Undeclared exception!
      try { 
        target0.__target__((float[]) null, floatArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      float[] floatArray0 = new float[12];
      float[] floatArray1 = new float[0];
      // Undeclared exception!
      try { 
        target0.__target__(floatArray0, floatArray1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      float[] floatArray0 = new float[4];
      float float0 = target0.__target__(floatArray0, floatArray0);
      assertEquals(0.0F, float0, 0.01F);
  }
}
